import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(path = "/") {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request(`http://localhost${path}`, { headers: { accept: path.startsWith("/api/") ? "application/json" : "text/html" } }),
    {
      ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) },
      DB: {},
    },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the MITO product shell", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>MITO — Tamil Nadu Land Intelligence<\/title>/i);
  assert.match(html, /Tamil Nadu land intelligence/i);
  assert.match(html, /Search village, Tamil name, SRO or ID/i);
  assert.match(html, /Expand to Chennai/i);
  assert.match(html, /24<!-- -->\/<!-- -->24/i);
  assert.match(html, /30(?:<!-- -->)? official planning records captured/i);
  assert.match(html, /1(?:<!-- -->)? archived TNREGINET street row recovered/i);
  assert.match(html, /All current village inventories verified/i);
  assert.match(html, /2,715(?:<!-- -->)? items across/i);
  assert.match(html, /2(?:<!-- -->)? official SIPCOT allotment rates captured/i);
  assert.match(html, /8(?:<!-- -->)? official TNHB residential price records/i);
  assert.match(html, /1(?:<!-- -->)? official liquidation reserve record/i);
  assert.match(html, /2(?:<!-- -->)? Siruseri commercial reserve events/i);
  assert.match(html, /5(?:<!-- -->)? Semmancheri industrial-land reserve events/i);
  assert.match(html, /2(?:<!-- -->)? Navalur residential-land reserve checkpoints/i);
  assert.match(html, /document-backed floors · incomplete history/i);
  assert.match(html, /6(?:<!-- -->)? Kazhipattur combined-asset reserve checkpoints/i);
  assert.match(html, /combined floors · not land values/i);
  assert.match(html, /1(?:<!-- -->)? Thaiyur land-auction reserve/i);
  assert.match(html, /unresolved between Thaiyur A and B/i);
  assert.match(html, /1(?:<!-- -->)? accepted Semmancheri land bid/i);
  assert.match(html, /cancelled before completion/i);
  assert.match(html, /8,017 sq-ft asset/i);
  assert.match(html, /land \+ building, not land rate/i);
  assert.match(html, /reserve price, not sale/i);
  assert.match(html, /closed original apartment offers/i);
  assert.match(html, /combined price, not land price/i);
  assert.match(html, /1(?:<!-- -->)? approximate footprint · (?:<!-- -->)?1(?:<!-- -->)? source point/i);
  assert.match(html, /Semmancheri point is an asset reference, not a parcel geometry/i);
  assert.match(html, /Not market price/i);
  assert.match(html, /Row-level publication needs permission/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});

test("pilot data preserves uncertainty and source provenance", async () => {
  const data = await readFile(new URL("../data/pilot.ts", import.meta.url), "utf8");
  assert.match(data, /tnreginet\.gov\.in\/portal/);
  assert.match(data, /eservices\.tn\.gov\.in/);
  assert.match(data, /Advertised asking price aggregate/);
  assert.match(data, /approximate-area-anchor/g);
  assert.match(data, /plotted:\s*false/g);
  assert.match(data, /not a property or parcel coordinate/gi);
  assert.doesNotMatch(data, /evidenceType:\s*["']registered_transaction["']/);
});

test("database schema separates sources, places, geometry, price and planning evidence", async () => {
  const schema = await readFile(new URL("../db/schema.ts", import.meta.url), "utf8");
  for (const entity of ["sources", "places", "geometries", "price_evidence", "verification_events", "coverage_scopes", "coverage_units", "source_capture_runs", "guideline_values", "planning_evidence"]) {
    assert.match(schema, new RegExp(`sqliteTable\\(\\\"${entity}\\\"`));
  }
  assert.match(schema, /evidence_type/);
  assert.match(schema, /registered_transaction/);
  assert.match(schema, /auction_reserve/);
  assert.match(schema, /positional_uncertainty_metres/);
});

test("coverage API publishes the honest OMR release gate", async () => {
  const response = await render("/api/coverage");
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.equal(payload.programme.id, "omr-corridor-2026");
  assert.equal(payload.programme.releaseReady, false);
  assert.equal(payload.summary.unitCount, 24);
  assert.equal(payload.summary.jurisdictionVerifiedCount, 24);
  assert.equal(payload.summary.currentStreetInventoryVerifiedCount, 24);
  assert.equal(payload.summary.currentOfficialInventoryItemCount, 2715);
  assert.equal(payload.summary.streetRegisterVerifiedCount, 0);
  assert.equal(payload.summary.officialGuidelineRecordCount, 0);
  assert.equal(payload.summary.archivedGuidelineRecordCount, 1);
  assert.equal(payload.summary.pendingGuidelineRecheckCount, 1);
  assert.equal(payload.summary.officialAllotmentRateCount, 2);
  assert.equal(payload.summary.officialAllotmentRateVillageCount, 1);
  assert.equal(payload.summary.officialAuctionReservePriceCount, 1);
  assert.equal(payload.summary.officialAuctionReservePriceVillageCount, 1);
  assert.equal(payload.summary.officialAuctionWinningBidRecordCount, 0);
  assert.equal(payload.summary.officialCommercialAuctionReserveCount, 2);
  assert.equal(payload.summary.officialCommercialAuctionAssetCount, 1);
  assert.equal(payload.summary.officialCommercialAuctionNamedParkAssociationCount, 1);
  assert.equal(payload.summary.officialCommercialAuctionDirectVillageLinkCount, 0);
  assert.equal(payload.summary.officialCommercialAuctionWinningBidRecordCount, 0);
  assert.equal(payload.summary.officialSecuredCreditorLandReserveCount, 5);
  assert.equal(payload.summary.officialSecuredCreditorLandReserveAssetCount, 1);
  assert.equal(payload.summary.officialSecuredCreditorLandReserveVillageCount, 1);
  assert.equal(payload.summary.officialSecuredCreditorLandReserveWinningBidRecordCount, 0);
  assert.equal(payload.summary.navalurResidentialLandReserveCount, 2);
  assert.equal(payload.summary.navalurResidentialLandReserveAssetCount, 1);
  assert.equal(payload.summary.navalurResidentialLandReserveVillageCount, 1);
  assert.equal(payload.summary.navalurResidentialLandReserveWinningBidRecordCount, 0);
  assert.equal(payload.summary.navalurResidentialLandReserveRegisteredTransactionCount, 0);
  assert.equal(payload.summary.navalurResidentialLandReserveUnnormalizedSecondaryClaimCount, 5);
  assert.equal(payload.summary.kazhipatturCombinedAssetReserveCount, 6);
  assert.equal(payload.summary.kazhipatturCombinedAssetReserveAssetCount, 2);
  assert.equal(payload.summary.kazhipatturCombinedAssetReserveVillageCount, 1);
  assert.equal(payload.summary.kazhipatturCombinedAssetLandReservePriceCount, 0);
  assert.equal(payload.summary.kazhipatturCombinedAssetWinningBidRecordCount, 0);
  assert.equal(payload.summary.kazhipatturCombinedAssetRegisteredTransactionCount, 0);
  assert.equal(payload.summary.officialUnresolvedThaiyurLandReserveCount, 1);
  assert.equal(payload.summary.officialUnresolvedThaiyurLandReserveAssetCount, 1);
  assert.equal(payload.summary.officialUnresolvedThaiyurCandidateVillageCount, 2);
  assert.equal(payload.summary.officialUnresolvedThaiyurDirectVillageLinkCount, 0);
  assert.equal(payload.summary.officialUnresolvedThaiyurWinningBidRecordCount, 0);
  assert.equal(payload.summary.officialAcceptedLandBidPriceObservationCount, 2);
  assert.equal(payload.summary.officialAcceptedLandBidAssetCount, 1);
  assert.equal(payload.summary.officialAcceptedLandBidVillageCount, 1);
  assert.equal(payload.summary.officialAcceptedLandBidRecordCount, 1);
  assert.equal(payload.summary.officialAcceptedLandBidCompletedSaleCount, 0);
  assert.equal(payload.summary.officialAcceptedLandBidRegisteredTransactionCount, 0);
  assert.equal(payload.summary.sourcePublishedAssetPointCount, 1);
  assert.equal(payload.summary.officialHousingOfferCount, 8);
  assert.equal(payload.summary.closedOfficialHousingOfferCount, 8);
  assert.equal(payload.summary.directHousingOfferVillageCount, 0);
  assert.equal(payload.summary.publishableApproximateGeometryCount, 1);
  assert.equal(payload.summary.exactEvidenceGeometryCount, 0);
  assert.equal(payload.summary.officialEvidenceGeometryPublishedCount, 0);
  assert.equal(payload.summary.officialPlanningRecordCount, 30);
  assert.equal(payload.offices.length, 6);
  assert.equal(payload.evidenceMatrix.length, 24);
  assert.ok(payload.evidenceMatrix.every((entry) => entry.currentGuidelineRegister.status === "verified_metadata_only"));
  assert.ok(payload.evidenceMatrix.every((entry) => entry.currentGuidelineRegister.currentPublishedValueCount === 0));
  assert.ok(payload.evidenceMatrix.every((entry) => entry.registeredTransactions.recordCount === 0));
  assert.ok(payload.evidenceMatrix.every((entry) => entry.publishedLandMarketValue.published === false));
  const siruseri = payload.evidenceMatrix.find((entry) => entry.key === "22604:800000275");
  assert.equal(siruseri.governmentAllotment.recordCount, 2);
  assert.equal(siruseri.officialCommercialAuctionReserves.status, "named_park_reserve_history_found");
  assert.equal(siruseri.officialCommercialAuctionReserves.recordCount, 2);
  assert.equal(siruseri.officialCommercialAuctionReserves.assetCount, 1);
  assert.equal(siruseri.officialCommercialAuctionReserves.directRecordCount, 0);
  assert.equal(siruseri.officialCommercialAuctionReserves.namedParkAssociationCount, 1);
  assert.deepEqual(siruseri.officialCommercialAuctionReserves.reservePriceRangeInr, { low: 281000000, high: 320000000 });
  assert.deepEqual(siruseri.officialCommercialAuctionReserves.derivedCombinedReserveRangeInrPerBuildingSqft, { low: 1964.76, high: 2237.45 });
  assert.equal(siruseri.officialCommercialAuctionReserves.landReservePriceRecordCount, 0);
  assert.equal(siruseri.officialCommercialAuctionReserves.registeredTransactionCount, 0);
  assert.equal(siruseri.officialCommercialAuctionReserves.winningBidRecordCount, 0);
  assert.equal(siruseri.geometry.publishableApproximateCount, 1);
  const sholinganallur1 = payload.evidenceMatrix.find((entry) => entry.key === "20066:254");
  assert.equal(sholinganallur1.officialAuctionReservePrices.status, "direct_reserve_price_record_found");
  assert.equal(sholinganallur1.officialAuctionReservePrices.recordCount, 1);
  assert.deepEqual(sholinganallur1.officialAuctionReservePrices.derivedReservePriceRangeInrPerSqft, { low: 4505.4, high: 4514.24 });
  assert.equal(sholinganallur1.officialAuctionReservePrices.registeredTransactionCount, 0);
  assert.equal(sholinganallur1.officialAuctionReservePrices.winningBidRecordCount, 0);
  const semmancheri = payload.evidenceMatrix.find((entry) => entry.key === "20066:246");
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.status, "direct_land_reserve_history_found");
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.recordCount, 5);
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.assetCount, 1);
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.directRecordCount, 5);
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.lifecycleAsOf, "2026-06-30");
  assert.deepEqual(semmancheri.officialSecuredCreditorLandReserves.reservePriceRangeInr, { low: 17955000, high: 19600000 });
  assert.deepEqual(semmancheri.officialSecuredCreditorLandReserves.derivedLandReserveRangeInrPerSqft, { low: 2239.62, high: 2444.8 });
  assert.equal(semmancheri.officialSecuredCreditorLandReserves.sourcePublishedPointCount, 1);
  assert.equal(semmancheri.geometry.sourcePublishedPointCount, 1);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.status, "accepted_bid_cancelled_no_completed_sale");
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.priceObservationCount, 2);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.acceptedBidRecordCount, 1);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.completedSaleRecordCount, 0);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.registeredTransactionCount, 0);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.reservePriceInr, 6800000);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.acceptedBidInr, 6870000);
  assert.equal(semmancheri.officialAcceptedLandBidOutcome.acceptedBidDerivedInrPerSqft, 3259.01);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.officialAuctionReservePrices.recordCount === 0).length, 23);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.officialCommercialAuctionReserves.recordCount === 0).length, 23);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.officialSecuredCreditorLandReserves.recordCount === 0).length, 23);
  const navalur = payload.evidenceMatrix.find((entry) => entry.key === "22604:800000277");
  assert.equal(navalur.navalurResidentialLandReserves.status, "direct_document_backed_reserve_checkpoints_found");
  assert.equal(navalur.navalurResidentialLandReserves.recordCount, 2);
  assert.equal(navalur.navalurResidentialLandReserves.assetCount, 1);
  assert.equal(navalur.navalurResidentialLandReserves.directRecordCount, 2);
  assert.deepEqual(navalur.navalurResidentialLandReserves.reservePriceRangeInr, { low: 4500000, high: 5736500 });
  assert.deepEqual(navalur.navalurResidentialLandReserves.derivedLandReserveRangeInrPerSqft, { low: 4314.48, high: 5500 });
  assert.equal(navalur.navalurResidentialLandReserves.verifiedCheckpointReductionPercent, 21.56);
  assert.equal(navalur.navalurResidentialLandReserves.completeReserveHistoryVerified, false);
  assert.equal(navalur.navalurResidentialLandReserves.unnormalizedSecondaryClaimCount, 5);
  assert.equal(navalur.navalurResidentialLandReserves.currentOfficialFeedTargetMatchCount, 0);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.navalurResidentialLandReserves.recordCount === 0).length, 23);
  const kazhipattur = payload.evidenceMatrix.find((entry) => entry.key === "22604:800000279");
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.status, "direct_combined_asset_reserve_checkpoints_found");
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.recordCount, 6);
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.assetCount, 2);
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.directRecordCount, 6);
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.combinedLandBuildingReserveRecordCount, 6);
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.landReservePriceRecordCount, 0);
  assert.equal(kazhipattur.kazhipatturCombinedAssetReserves.completeReserveHistoryVerified, false);
  assert.deepEqual(kazhipattur.kazhipatturCombinedAssetReserves.assetComparisons.map((asset) => asset.verifiedCheckpointChangePercent), [-4.96, 15.87]);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.kazhipatturCombinedAssetReserves.recordCount === 0).length, 23);
  for (const key of ["22605:800000289", "22605:800000290"]) {
    const thaiyur = payload.evidenceMatrix.find((entry) => entry.key === key);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.status, "unresolved_registration_subdivision");
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.recordCount, 1);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.directRecordCount, 0);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.candidateAssociationCount, 1);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.derivedReservePriceInrPerSqft, 1620.49);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.registeredTransactionCount, 0);
    assert.equal(thaiyur.officialUnresolvedThaiyurLandReserve.winningBidRecordCount, 0);
  }
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.officialUnresolvedThaiyurLandReserve.recordCount === 0).length, 22);
  for (const key of ["20066:254", "20066:20514"]) {
    const sholinganallur = payload.evidenceMatrix.find((entry) => entry.key === key);
    assert.equal(sholinganallur.tnhbPublicSales.status, "unresolved_locality_match");
    assert.equal(sholinganallur.tnhbPublicSales.unresolvedRecordCount, 8);
    assert.equal(sholinganallur.tnhbPublicSales.directRecordCount, 0);
  }
  assert.equal(payload.evidenceMatrix.find((entry) => entry.key === "20066:254").planning.directRecordCount, 1);
  assert.equal(payload.evidenceMatrix.find((entry) => entry.key === "20066:20514").planning.directRecordCount, 0);
  assert.equal(payload.evidenceMatrix.find((entry) => entry.key === "20066:246").planning.directRecordCount, 4);
  assert.equal(payload.evidenceMatrix.find((entry) => entry.key === "20066:250").planning.directRecordCount, 3);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.planning.status === "no_direct_record_in_ledger").length, 2);
  assert.equal(payload.evidenceMatrix.filter((entry) => entry.tnhbPublicSales.status === "no_normalized_place_name_match_in_snapshot").length, 22);
});

test("evidence API publishes planning provenance, current register metadata and the rights gate", async () => {
  const response = await render("/api/evidence");
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.equal(payload.scopeId, "omr-corridor-2026");
  assert.equal(payload.planning.summary.recordCount, 30);
  assert.equal(payload.planning.summary.linkedRecordCount, 27);
  assert.equal(payload.planning.summary.villageCount, 22);
  assert.equal(payload.planning.summary.unresolvedRecordCount, 3);
  assert.equal(payload.planning.summary.sourceCount, 12);
  assert.equal(payload.planning.records.length, 30);
  assert.equal(payload.planning.indexAudits[0].indexPageCount, 30);
  const semmancheriPlan = payload.planning.records.find((record) => record.id === "cmda-pp-nhrb-s-0167-2025-semmancheri");
  assert.equal(semmancheriPlan.siteMetrics.fsiFactor, 1.917);
  assert.equal(semmancheriPlan.siteMetrics.landLeftForRoadWideningSqm, 16.8);
  assert.equal(semmancheriPlan.siteMetrics.localBodyBuildingPermitRequired, true);
  assert.equal(semmancheriPlan.geometryStatus, "unplotted");
  assert.equal(semmancheriPlan.privacy.personalDataFieldsStored, 0);
  const thoraipakkamPlan = payload.planning.records.find((record) => record.id === "cmda-pp-nhrb-s-0429-2022-okkiyam-thoraipakkam");
  assert.equal(thoraipakkamPlan.siteMetrics.fsiFactor, 2.477);
  assert.equal(thoraipakkamPlan.siteMetrics.totalFsiAreaSqm, 3427.51);
  assert.equal(thoraipakkamPlan.siteMetrics.localBodyBuildingPermitRequired, true);
  assert.equal(thoraipakkamPlan.geometryStatus, "unplotted");
  assert.equal(thoraipakkamPlan.privacy.personalDataFieldsStored, 0);
  assert.equal(payload.officialAllotmentRates.summary.recordCount, 2);
  assert.equal(payload.officialAllotmentRates.summary.villageAssociationCount, 1);
  assert.deepEqual(payload.officialAllotmentRates.summary.normalizedRateRangeInrPerSqft, { low: 1790.63, high: 3581.27 });
  assert.equal(payload.officialAllotmentRates.source.rightsStatus, "no_explicit_reuse_policy_found");
  assert.equal(payload.officialAllotmentRates.location.geometryStatus, "approximate");
  assert.equal(payload.officialAllotmentRates.location.geometryId, "osm-way-98358103");
  assert.equal(payload.officialAllotmentRates.location.currentRegistrationAssociation.status, "named_locality_association");
  assert.equal(payload.officialAllotmentRates.records[0].evidenceType, "government_allotment_plot_cost");
  assert.equal(payload.officialAllotmentRates.records[0].tenure, "99_year_leasehold");
  assert.equal(payload.officialAllotmentRates.records[0].normalizedInrPerSqft, 1790.63);
  assert.equal(payload.officialAllotmentRates.records[1].normalizedInrPerSqft, 3581.27);
  assert.equal(payload.officialAllotmentRates.publication.currentOfficialGuidelineValues, 0);
  assert.equal(payload.officialAllotmentRates.publication.registeredTransactions, 0);
  assert.equal(payload.officialAllotmentRates.subsidy.appliedToPublishedRates, false);
  assert.equal(payload.officialHousingOffers.summary.recordCount, 8);
  assert.equal(payload.officialHousingOffers.summary.currentOfferCount, 0);
  assert.equal(payload.officialHousingOffers.summary.closedOfferCount, 8);
  assert.equal(payload.officialHousingOffers.summary.directVillageLinkCount, 0);
  assert.deepEqual(payload.officialHousingOffers.summary.originalSellingPriceRangeInr, { low: 1043000, high: 6652000 });
  assert.deepEqual(payload.officialHousingOffers.summary.derivedCombinedPriceRangeInrPerPlinthSqft, { low: 2349.1, high: 6110.59 });
  assert.equal(payload.officialHousingOffers.source.sourceResponseRecordCount, 183);
  assert.equal(payload.officialHousingOffers.source.targetRecordCount, 8);
  assert.equal(payload.officialHousingOffers.source.rightsStatus, "no_explicit_reuse_policy_found");
  assert.equal(payload.officialHousingOffers.location.mappingStatus, "unresolved_registration_subdivision");
  assert.deepEqual(payload.officialHousingOffers.location.candidateVillageKeys, ["20066:254", "20066:20514"]);
  assert.equal(payload.officialHousingOffers.location.directVillageLink, false);
  assert.equal(payload.officialHousingOffers.priceInterpretation.landPriceDerivationPermitted, false);
  assert.equal(payload.officialHousingOffers.records.length, 8);
  assert.ok(payload.officialHousingOffers.records.every((record) => record.offerStatusAtAudit === "closed" && record.geometryStatus === "unplotted"));
  assert.equal(payload.officialHousingOffers.publication.landPriceRecords, 0);
  assert.equal(payload.officialHousingOffers.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialHousingOffers.publicationRule, /must never be relabelled as a land price/i);
  assert.equal(payload.officialAuctionReservePrices.summary.recordCount, 1);
  assert.equal(payload.officialAuctionReservePrices.summary.directVillageLinkCount, 1);
  assert.equal(payload.officialAuctionReservePrices.summary.registeredTransactionCount, 0);
  assert.equal(payload.officialAuctionReservePrices.summary.winningBidRecordCount, 0);
  assert.deepEqual(payload.officialAuctionReservePrices.summary.derivedReservePriceRangeInrPerSqft, { low: 4505.4, high: 4514.24 });
  assert.equal(payload.officialAuctionReservePrices.location.officialVillageCode, "254");
  assert.equal(payload.officialAuctionReservePrices.location.geometryStatus, "unplotted");
  assert.equal(payload.officialAuctionReservePrices.asset.documentAreaSqft, 426888);
  assert.equal(payload.officialAuctionReservePrices.records[0].lifecycleStatus, "auction_concluded_outcome_price_unpublished");
  assert.equal(payload.officialAuctionReservePrices.records[0].winningBidInr, null);
  assert.equal(payload.officialAuctionReservePrices.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialAuctionReservePrices.publicationRule, /must never be relabelled as the winning bid/i);
  assert.equal(payload.officialCommercialAuctionReserves.summary.recordCount, 2);
  assert.equal(payload.officialCommercialAuctionReserves.summary.assetCount, 1);
  assert.equal(payload.officialCommercialAuctionReserves.summary.namedParkAssociationCount, 1);
  assert.equal(payload.officialCommercialAuctionReserves.summary.directVillageLinkCount, 0);
  assert.equal(payload.officialCommercialAuctionReserves.summary.landReservePriceRecordCount, 0);
  assert.equal(payload.officialCommercialAuctionReserves.summary.registeredTransactionCount, 0);
  assert.equal(payload.officialCommercialAuctionReserves.summary.winningBidRecordCount, 0);
  assert.deepEqual(payload.officialCommercialAuctionReserves.summary.reservePriceRangeInr, { low: 281000000, high: 320000000 });
  assert.deepEqual(payload.officialCommercialAuctionReserves.summary.derivedCombinedReserveRangeInrPerBuildingSqft, { low: 1964.76, high: 2237.45 });
  assert.equal(payload.officialCommercialAuctionReserves.location.mappingStatus, "named_park_association");
  assert.equal(payload.officialCommercialAuctionReserves.location.directVillageLink, false);
  assert.equal(payload.officialCommercialAuctionReserves.location.geometryStatus, "unplotted");
  assert.equal(payload.officialCommercialAuctionReserves.asset.plotNumber, "A-17");
  assert.equal(payload.officialCommercialAuctionReserves.asset.buildingAreaSqft, 143020);
  assert.equal(payload.officialCommercialAuctionReserves.records.length, 2);
  assert.equal(payload.officialCommercialAuctionReserves.records[1].totalReservePriceInr, 281000000);
  assert.equal(payload.officialCommercialAuctionReserves.records[1].winningBidInr, null);
  assert.equal(payload.officialCommercialAuctionReserves.reconciliation.reserveReductionPercent, 12.19);
  assert.equal(payload.officialCommercialAuctionReserves.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialCommercialAuctionReserves.publicationRule, /must never be relabelled as a land rate/i);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.recordCount, 5);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.assetCount, 1);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.directVillageLinkCount, 1);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.registeredTransactionCount, 0);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.winningBidRecordCount, 0);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.sourcePublishedPointCount, 1);
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.exactParcelGeometryCount, 0);
  assert.deepEqual(payload.officialSecuredCreditorLandReserves.summary.reservePriceRangeInr, { low: 17955000, high: 19600000 });
  assert.deepEqual(payload.officialSecuredCreditorLandReserves.summary.derivedLandReserveRangeInrPerSqft, { low: 2239.62, high: 2444.8 });
  assert.equal(payload.officialSecuredCreditorLandReserves.summary.reserveReductionPercent, 8.39);
  assert.equal(payload.officialSecuredCreditorLandReserves.location.officialVillageCode, "246");
  assert.equal(payload.officialSecuredCreditorLandReserves.location.geometryStatus, "source_published_point");
  assert.deepEqual(payload.officialSecuredCreditorLandReserves.location.geometry.coordinates, [80.229881, 12.874384]);
  assert.equal(payload.officialSecuredCreditorLandReserves.asset.landAreaSqft, 8017);
  assert.equal(payload.officialSecuredCreditorLandReserves.asset.currentLifecycleAsOf, "2026-06-30");
  assert.equal(payload.officialSecuredCreditorLandReserves.records.length, 5);
  assert.equal(payload.officialSecuredCreditorLandReserves.records.at(-1).winningBidInr, null);
  assert.equal(payload.officialSecuredCreditorLandReserves.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialSecuredCreditorLandReserves.publicationRule, /source point is not a parcel boundary/i);
  assert.equal(payload.navalurResidentialLandReserves.summary.recordCount, 2);
  assert.equal(payload.navalurResidentialLandReserves.summary.assetCount, 1);
  assert.equal(payload.navalurResidentialLandReserves.summary.directVillageLinkCount, 1);
  assert.equal(payload.navalurResidentialLandReserves.summary.completedSaleRecordCount, 0);
  assert.equal(payload.navalurResidentialLandReserves.summary.registeredTransactionCount, 0);
  assert.equal(payload.navalurResidentialLandReserves.summary.winningBidRecordCount, 0);
  assert.deepEqual(payload.navalurResidentialLandReserves.summary.reservePriceRangeInr, { low: 4500000, high: 5736500 });
  assert.deepEqual(payload.navalurResidentialLandReserves.summary.derivedLandReserveRangeInrPerSqft, { low: 4314.48, high: 5500 });
  assert.equal(payload.navalurResidentialLandReserves.summary.completeReserveHistoryVerified, false);
  assert.equal(payload.navalurResidentialLandReserves.location.officialVillageCode, "800000277");
  assert.equal(payload.navalurResidentialLandReserves.location.geometryStatus, "unplotted");
  assert.equal(payload.navalurResidentialLandReserves.asset.landAreaSqft, 1043);
  assert.equal(payload.navalurResidentialLandReserves.records.length, 2);
  assert.equal(payload.navalurResidentialLandReserves.records.at(-1).winningBidInr, null);
  assert.equal(payload.navalurResidentialLandReserves.secondaryClaims.claims.length, 5);
  assert.equal(payload.navalurResidentialLandReserves.secondaryClaims.normalizedRecordCount, 0);
  assert.equal(payload.navalurResidentialLandReserves.officialCurrentFeedAudit.targetMatchCount, 0);
  assert.equal(payload.navalurResidentialLandReserves.publication.personalDataFieldsStored, 0);
  assert.match(payload.navalurResidentialLandReserves.publicationRule, /must never be relabelled as winning bids/i);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.recordCount, 6);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.assetCount, 2);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.directVillageLinkCount, 1);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.landReservePriceRecordCount, 0);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.completedSaleRecordCount, 0);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.winningBidRecordCount, 0);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.registeredTransactionCount, 0);
  assert.equal(payload.kazhipatturCombinedAssetReserves.summary.completeReserveHistoryVerified, false);
  assert.equal(payload.kazhipatturCombinedAssetReserves.location.officialVillageCode, "800000279");
  assert.equal(payload.kazhipatturCombinedAssetReserves.location.geometryStatus, "unplotted");
  assert.deepEqual(payload.kazhipatturCombinedAssetReserves.assets.map((asset) => asset.landAreaSqft), [4344, 3012]);
  assert.equal(payload.kazhipatturCombinedAssetReserves.assets[1].buildingAreaSqft, null);
  assert.equal(payload.kazhipatturCombinedAssetReserves.records.length, 6);
  assert.ok(payload.kazhipatturCombinedAssetReserves.records.every((record) => !record.isLandReservePrice && record.winningBidInr === null));
  assert.equal(payload.kazhipatturCombinedAssetReserves.publication.personalDataFieldsStored, 0);
  assert.match(payload.kazhipatturCombinedAssetReserves.publicationRule, /must never be relabelled as winning bids/i);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.summary.recordCount, 1);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.summary.directVillageLinkCount, 0);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.summary.registeredTransactionCount, 0);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.summary.winningBidRecordCount, 0);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.summary.derivedReservePriceInrPerSqft, 1620.49);
  assert.deepEqual(payload.officialUnresolvedThaiyurLandReserve.location.candidateVillageKeys, ["22605:800000289", "22605:800000290"]);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.location.directVillageLink, false);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.location.geometryStatus, "unplotted");
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.asset.landAreaSqft, 693);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.records[0].winningBidInr, null);
  assert.equal(payload.officialUnresolvedThaiyurLandReserve.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialUnresolvedThaiyurLandReserve.publicationRule, /must never be relabelled as a winning bid/i);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.priceObservationCount, 2);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.acceptedBidRecordCount, 1);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.completedSaleRecordCount, 0);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.registeredTransactionCount, 0);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.acceptedBidInr, 6870000);
  assert.equal(payload.officialAcceptedLandBidOutcome.summary.acceptedBidDerivedInrPerSqft, 3259.01);
  assert.equal(payload.officialAcceptedLandBidOutcome.sourceAuthority.officialOrderUrlLocated, false);
  assert.equal(payload.officialAcceptedLandBidOutcome.sourceAuthority.mirrorPromotedAsOfficialSource, false);
  assert.equal(payload.officialAcceptedLandBidOutcome.location.officialVillageCode, "246");
  assert.equal(payload.officialAcceptedLandBidOutcome.location.directVillageLink, true);
  assert.equal(payload.officialAcceptedLandBidOutcome.location.geometryStatus, "unplotted");
  assert.equal(payload.officialAcceptedLandBidOutcome.asset.landAreaSqft, 2108);
  assert.equal(payload.officialAcceptedLandBidOutcome.priceObservations[1].isWinningBid, true);
  assert.equal(payload.officialAcceptedLandBidOutcome.priceObservations[1].isCompletedSale, false);
  assert.equal(payload.officialAcceptedLandBidOutcome.publication.personalDataFieldsStored, 0);
  assert.match(payload.officialAcceptedLandBidOutcome.publicationRule, /must never be relabelled as a completed sale/i);
  assert.equal(payload.geometryEvidence.summary.publishableGeometryCount, 1);
  assert.equal(payload.geometryEvidence.summary.approximateGeometryCount, 1);
  assert.equal(payload.geometryEvidence.summary.exactGeometryCount, 0);
  assert.equal(payload.geometryEvidence.summary.officialGeometryPublishedCount, 0);
  assert.equal(payload.geometryEvidence.decision.officialBoundaryClaim, false);
  assert.equal(payload.geometryEvidence.officialVerificationSource.geometryPublishedByMito, false);
  assert.equal(payload.geometryEvidence.openSource.objectId, 98358103);
  assert.equal(payload.geometryEvidence.openSource.license, "ODbL-1.0");
  assert.equal(payload.geometryEvidence.comparison.openCentroidInsideOfficialBoundary, true);
  assert.equal(payload.geometryEvidence.featureCollection.features[0].properties.geometryStatus, "approximate");
  assert.equal(payload.guidelineValueCollection.captureRun.status, "blocked");
  assert.equal(payload.guidelineValueCollection.captureRun.recordsSeen, 10);
  assert.equal(payload.guidelineValueCollection.captureRun.recordsAccepted, 0);
  assert.equal(payload.guidelineValueCollection.captureRun.recordsWithheld, 10);
  assert.equal(payload.guidelineValueCollection.captureRun.blockerCode, "REDISTRIBUTION_PERMISSION_REQUIRED");
  assert.equal(payload.guidelineValueCollection.archivedSnapshot.summary.recordCount, 1);
  assert.equal(payload.guidelineValueCollection.archivedSnapshot.summary.verifiedCurrentCount, 0);
  assert.equal(payload.guidelineValueCollection.archivedSnapshot.records[0].sourceStreetName, "CHIDAMBARAM NAGAR 1ST STREET");
  assert.equal(payload.guidelineValueCollection.archivedSnapshot.records[0].valueInrPerSqft, 4400);
  assert.equal(payload.guidelineValueCollection.archivedSnapshot.records[0].verificationStatus, "pending");
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.auditedVillageCount, 24);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.targetVillageCount, 24);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.currentInventoryCount, 2715);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.sholinganallur1InventoryCount, 758);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.currentOfficialRowsStored, 0);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.currentOfficialValuesPublished, 0);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.summary.permissionRequired, true);
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.queries.length, 24);
  assert.ok(payload.guidelineValueCollection.currentOfficialRegister.queries.every((query) => query.rowDataRepublished === false));
  assert.equal(payload.guidelineValueCollection.currentOfficialRegister.reconciliation.status, "resolved_for_current_inventory");
  assert.equal(payload.guidelineValueCollection.secondaryCorroboration.summary.matchedRowCount, 1);
  assert.equal(payload.guidelineValueCollection.secondaryCorroboration.summary.exactFieldMatchCount, 1);
  assert.equal(payload.guidelineValueCollection.secondaryCorroboration.summary.currentOfficialPromotionCount, 0);
  assert.equal(payload.guidelineValueCollection.secondaryCorroboration.scopeClaims.claimedStreetCount, 758);
  assert.equal(payload.guidelineValueCollection.secondaryCorroboration.conflicts[0].status, "resolved_for_current_inventory");
  assert.equal(payload.guidelineValueCollection.importContract.schemaVersion, "1.1.0");
  assert.ok(payload.guidelineValueCollection.importContract.requiredRowFields.includes("officialStreetCode"));
});

test("resolver API matches verified portal variants and official identifiers", async () => {
  const variantResponse = await render("/api/resolve?query=Tharamani");
  assert.equal(variantResponse.status, 200);
  const variant = await variantResponse.json();
  assert.equal(variant.result.status, "matched");
  assert.equal(variant.result.confidence, "variant");
  assert.equal(variant.result.matches.length, 1);
  assert.equal(variant.result.matches[0].unit.nameEn, "Taramani");
  assert.equal(variant.result.matches[0].inventoryQuery.guidelineVillageName, "Tharamani");

  const codeResponse = await render("/api/resolve?query=20066%3A253");
  assert.equal(codeResponse.status, 200);
  const code = await codeResponse.json();
  assert.equal(code.result.status, "matched");
  assert.equal(code.result.confidence, "exact");
  assert.equal(code.result.matches[0].unit.nameEn, "Seevaram");
});

test("resolver API preserves ambiguity, Tamil aliases and unresolved conflicts", async () => {
  const ambiguousResponse = await render("/api/resolve?query=Sholinganallur");
  assert.equal(ambiguousResponse.status, 200);
  const ambiguous = await ambiguousResponse.json();
  assert.equal(ambiguous.result.status, "ambiguous");
  assert.deepEqual(ambiguous.result.matches.map((match) => match.key), ["20066:254", "20066:20514"]);

  const tamilResponse = await render("/api/resolve?query=%E0%AE%9A%E0%AF%86%E0%AE%AE%E0%AF%8D%E0%AE%AE%E0%AE%9E%E0%AF%8D%E0%AE%9A%E0%AF%87%E0%AE%B0%E0%AE%BF");
  assert.equal(tamilResponse.status, 200);
  const tamil = await tamilResponse.json();
  assert.equal(tamil.result.status, "matched");
  assert.equal(tamil.result.matches[0].unit.nameEn, "Semmancheri");

  const unresolvedResponse = await render("/api/resolve?query=Kalipattur");
  assert.equal(unresolvedResponse.status, 200);
  const unresolved = await unresolvedResponse.json();
  assert.equal(unresolved.result.status, "unresolved");
  assert.equal(unresolved.result.matches.length, 0);
  assert.match(unresolved.result.explanation, /does not merge/i);
});

test("Chennai coverage API publishes the source inventory and unresolved official conflict", async () => {
  const response = await render("/api/chennai-coverage");
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.equal(payload.scopeId, "chennai-district-revenue-2026");
  assert.equal(payload.summary.talukGroupCount, 17);
  assert.equal(payload.summary.sourceVillageCount, 144);
  assert.equal(payload.summary.firkaCount, 49);
  assert.equal(payload.summary.registrationCrosswalkCount, 9);
  assert.equal(payload.summary.ambiguousRegistrationCrosswalkCount, 3);
  assert.equal(payload.summary.currentInventoryMetadataCount, 9);
  assert.equal(payload.summary.currentInventoryItemCount, 2117);
  assert.equal(payload.summary.officialGuidelineValueCount, 0);
  assert.equal(payload.summary.registeredTransactionCount, 0);
  assert.equal(payload.summary.plottedGeometryCount, 0);
  assert.equal(payload.summary.authoritativeRoadFeaturesDiscovered, 37225);
  assert.equal(payload.summary.authoritativeWardPolygonsDiscovered, 200);
  assert.equal(payload.summary.authoritativeZonePolygonsDiscovered, 15);
  assert.equal(payload.summary.publishableAuthoritativeGeometryCount, 0);
  assert.equal(payload.summary.geometryPermissionGatedSourceCount, 3);
  assert.equal(payload.summary.conflictCount, 1);
  assert.equal(payload.taluks.length, 17);
  assert.equal(payload.talukCrosswalkProgress.find((taluk) => taluk.talukName === "Velachery").verifiedCrosswalkCount, 2);
  assert.equal(payload.talukCrosswalkProgress.find((taluk) => taluk.talukName === "Sholinganallur").verifiedCrosswalkCount, 7);
  assert.equal(payload.registrationCrosswalk.summary.currentOfficialValuesPublished, 0);
  assert.equal(payload.geometrySourceAudit.decision.status, "permission_required");
  assert.equal(payload.geometrySourceAudit.summary.officialGeometryFeaturesPublished, 0);
  assert.equal(payload.geometrySourceAudit.sources[0].technicalEvidence.nativeCrs, "EPSG:32644");
  assert.equal(payload.conflicts[0].status, "unresolved");
});

test("Chennai resolver exposes a verified registration identity without inventing a price", async () => {
  const response = await render("/api/chennai-coverage?query=Taramani");
  assert.equal(response.status, 200);
  const payload = await response.json();
  const match = payload.resolution.matches[0];
  assert.equal(payload.resolution.status, "matched");
  assert.equal(match.key, "8:3");
  assert.equal(match.registrationCrosswalkStatus, "verified");
  assert.equal(match.registrationCrosswalk.officialSroCode, "20051");
  assert.equal(match.registrationCrosswalk.officialVillageCode, "7");
  assert.equal(match.registrationCrosswalk.currentInventoryItemCount, 80);
  assert.equal(match.officialGuidelineValues, 0);
  assert.equal(match.registeredTransactions, 0);
  assert.equal(match.geometryStatus, "unplotted");
});

test("Chennai resolver keeps duplicate village names separate by taluk", async () => {
  const response = await render("/api/chennai-coverage?query=Alandur");
  assert.equal(response.status, 200);
  const payload = await response.json();
  assert.equal(payload.resolution.status, "ambiguous");
  assert.equal(payload.resolution.matches.length, 2);
  assert.deepEqual(payload.resolution.matches.map((match) => match.talukName), ["Guindy", "Alandur"]);
  assert.ok(payload.resolution.matches.every((match) => match.registrationCrosswalkStatus === "not_started"));
});
