import {
  guidelineValueImportSchema,
  omrGuidelineCaptureRun,
  omrGuidelineLiveRegisterAudit,
  omrGuidelineLiveRegisterSummary,
  omrGuidelineOmrInventoryAudit,
  omrGuidelineSecondaryCorroborationLedger,
  omrGuidelineSecondaryCorroborationSummary,
  omrGuidelineSnapshotLedger,
  omrGuidelineSnapshotSummary,
  omrOfficialAllotmentRateLedger,
  omrOfficialAllotmentRateSummary,
  omrOfficialAuctionReservePriceLedger,
  omrOfficialAuctionReservePriceSummary,
  omrPlanningLedger,
  omrPlanningSummary,
  omrSiruseriFootprint,
  omrSiruseriGeometryAudit,
  omrTnhbHousingOfferLedger,
  omrTnhbHousingOfferSummary,
  unresolvedPlanningRecords,
} from "../../../data/evidence";

export async function GET() {
  return Response.json({
    generatedAt: "2026-07-17",
    scopeId: omrPlanningLedger.scopeId,
    planning: {
      summary: omrPlanningSummary,
      methodology: omrPlanningLedger.methodology,
      coverageCaveat: omrPlanningLedger.coverageCaveat,
      indexAudits: omrPlanningLedger.indexAudits,
      sources: omrPlanningLedger.sources,
      records: omrPlanningLedger.records,
      unresolvedCrosswalks: unresolvedPlanningRecords,
    },
    officialAllotmentRates: {
      summary: omrOfficialAllotmentRateSummary,
      source: omrOfficialAllotmentRateLedger.source,
      tenureEvidence: omrOfficialAllotmentRateLedger.tenureEvidence,
      location: omrOfficialAllotmentRateLedger.location,
      subsidy: omrOfficialAllotmentRateLedger.subsidy,
      records: omrOfficialAllotmentRateLedger.records,
      publication: omrOfficialAllotmentRateLedger.publication,
      publicationRule: "These rows are SIPCOT leasehold allotment plot costs. They must never be relabelled as guideline values, registered transactions, asking prices, market estimates or a village-wide Siruseri rate.",
    },
    officialHousingOffers: {
      summary: omrTnhbHousingOfferSummary,
      source: omrTnhbHousingOfferLedger.source,
      location: omrTnhbHousingOfferLedger.location,
      priceInterpretation: omrTnhbHousingOfferLedger.priceInterpretation,
      records: omrTnhbHousingOfferLedger.records,
      publication: omrTnhbHousingOfferLedger.publication,
      publicationRule: "These are closed historical TNHB original combined apartment selling prices. The derived per-square-foot metric uses plinth area only; it must never be relabelled as a land price, guideline value, registered transaction, current asking price, market estimate or village-wide Sholinganallur rate. The unresolved Sholinganallur 1/2 crosswalk prevents direct village attribution.",
    },
    officialAuctionReservePrices: {
      summary: omrOfficialAuctionReservePriceSummary,
      sources: omrOfficialAuctionReservePriceLedger.sources,
      privacy: omrOfficialAuctionReservePriceLedger.privacy,
      location: omrOfficialAuctionReservePriceLedger.location,
      asset: omrOfficialAuctionReservePriceLedger.asset,
      records: omrOfficialAuctionReservePriceLedger.records,
      conflicts: omrOfficialAuctionReservePriceLedger.conflicts,
      publication: omrOfficialAuctionReservePriceLedger.publication,
      publicationRule: "This is a liquidation-auction reserve price derived against two published area totals. It must never be relabelled as the winning bid, registered sale consideration, guideline value, asking price, market estimate, current availability or a village-wide Sholinganallur rate.",
    },
    geometryEvidence: {
      summary: omrSiruseriGeometryAudit.publication,
      decision: omrSiruseriGeometryAudit.decision,
      officialVerificationSource: omrSiruseriGeometryAudit.officialSource,
      openSource: omrSiruseriGeometryAudit.openSource,
      comparison: omrSiruseriGeometryAudit.comparison,
      featureCollection: omrSiruseriFootprint,
      publicationRule: "MITO publishes only the ODbL-licensed approximate OSM footprint. The official SIPCOT boundary is neither stored nor republished, and the open footprint must never be described as official, exact, cadastral, legal or complete.",
    },
    guidelineValueCollection: {
      captureRun: omrGuidelineCaptureRun,
      archivedSnapshot: {
        summary: omrGuidelineSnapshotSummary,
        source: omrGuidelineSnapshotLedger.source,
        records: omrGuidelineSnapshotLedger.rows,
        publicationRule: "Archived snapshot rows remain pending and unplotted until the live official source is rechecked. They are excluded from current verified totals.",
      },
      currentOfficialRegister: {
        summary: omrGuidelineLiveRegisterSummary,
        source: omrGuidelineOmrInventoryAudit.source,
        retrievalPath: omrGuidelineOmrInventoryAudit.retrievalPath,
        queries: omrGuidelineOmrInventoryAudit.queries,
        reconciliation: omrGuidelineLiveRegisterAudit.reconciliation,
        publication: omrGuidelineOmrInventoryAudit.publication,
        limitations: omrGuidelineOmrInventoryAudit.limitations,
        publicationRule: "MITO publishes the 24 current official village inventory counts and retrieval metadata, but no row-level register content until Registration Department reuse permission or an authorized licence is confirmed.",
      },
      secondaryCorroboration: {
        summary: omrGuidelineSecondaryCorroborationSummary,
        audit: omrGuidelineSecondaryCorroborationLedger.audit,
        scopeClaims: omrGuidelineSecondaryCorroborationLedger.scopeClaims,
        matchedRows: omrGuidelineSecondaryCorroborationLedger.matchedRows,
        conflicts: omrGuidelineSecondaryCorroborationLedger.conflicts,
        publicationRule: "A third-party field match is a discovery and transcription-check signal only. It cannot increase current official coverage or pass a release gate.",
      },
      importContract: {
        id: guidelineValueImportSchema.$id,
        schemaVersion: guidelineValueImportSchema.properties.schemaVersion.const,
        requiredBatchFields: guidelineValueImportSchema.required,
        requiredRowFields: guidelineValueImportSchema.properties.rows.items.required,
      },
    },
  });
}
